services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: ./public
          action: rebuild
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: .
          action: sync
          target: /app