services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: "yarn dev"
    develop:
      watch:
        # - path: ./src
        #   action: rebuild
        - path: ./public
          action: rebuild
        - path: ./package.json
          action: rebuild
        - path: .
          action: sync
          target: /app
          